"""Playground device registry. Separate from auth sessions and subscriptions.

``rtc_device`` identifies an installation. ``rtc_session`` authenticates a login.
Device restriction applies only to paid Playground, never Constitution or /laws.

Supported platforms are ``web``, ``android``, and ``ios``. Native mobile
clients use the same installation-token security model:

Android:
    random installation token generated by the app
    stored securely by the app
    never hardware-derived

iOS:
    random installation token generated by the app
    stored securely in Keychain / app secure storage
    never hardware-derived

Do not use IDFV, IDFA, IMEI, serial number, MAC address, hardware UUID, or a
device fingerprint as RecallC device identity. Web Safari on iPhone remains
``platform=web`` (website cookie). A native iOS app supplies ``platform=ios``.
This repository does not ship mobile client code.
"""

from constitution_memorizer.devices.models import (
    BLOCK_DEVICE_CONFIG_ERROR,
    BLOCK_DEVICE_LIMIT,
    BLOCK_DEVICE_REVOKED,
    DEVICE_BLOCK_REASONS,
    DEVICE_PLATFORMS,
    PLATFORM_ANDROID,
    PLATFORM_IOS,
    PLATFORM_WEB,
    DeviceAccess,
    DeviceSummary,
    UserDevice,
    UserDeviceSession,
    require_platform,
)
from constitution_memorizer.devices.service import DeviceService
from constitution_memorizer.devices.token import (
    DEVICE_COOKIE_NAME,
    hash_device_token,
    mint_installation_token,
)

DEVICES_MANAGE_PATH = "/profile/security/devices"

__all__ = [
    "BLOCK_DEVICE_CONFIG_ERROR",
    "BLOCK_DEVICE_LIMIT",
    "BLOCK_DEVICE_REVOKED",
    "DEVICE_BLOCK_REASONS",
    "DEVICE_COOKIE_NAME",
    "DEVICE_PLATFORMS",
    "DEVICES_MANAGE_PATH",
    "DeviceAccess",
    "DeviceService",
    "DeviceSummary",
    "PLATFORM_ANDROID",
    "PLATFORM_IOS",
    "PLATFORM_WEB",
    "UserDevice",
    "UserDeviceSession",
    "hash_device_token",
    "mint_installation_token",
    "require_platform",
]
